name: Android CI - Tests

on:
  pull_request:

jobs:
  build-and-test:
    name: Unit + Instrumentation tests
    runs-on: ubuntu-latest
    env:
      JAVA_TOOL_OPTIONS: "-XX:+UseContainerSupport"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute for gradlew
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew test --no-daemon --parallel --build-cache --stacktrace

      - name: Start Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          target: google_apis
          force-avd-creation: true
          emulator-options: -no-window -no-audio -no-boot-anim

      - name: Wait for emulator to be ready
        run: |
          adb wait-for-device
          adb shell getprop sys.boot_completed | grep -m 1 '1'

      - name: Run instrumentation tests
        run: ./gradlew connectedDebugAndroidTest --no-daemon --build-cache --stacktrace
